#!/bin/bash

source ./config/script/functions

COURSE=$(check-course)

if [[ -z "${COURSE}" ]]
then 	
    echo "Please use right course abbreviation"
    list-courses
    exit 1
fi

set -a
source ./config/course/"${COURSE}"

[[ -z "${LABS}" ]] || lab ${LABS}
[[ -z "${PROJECT_PERSONAL}" ]] || project-personal ${PROJECT_PERSONAL}
[[ -z "${PROJECT_GROUP}" ]] || project-group ${PROJECT_GROUP}




