#!/bin/bash

for i in $@
do
    mkdir -p project-personal/stage"${i}"
    cp -R template/report/report project-personal/stage"${i}"
    cp -R template/presentation/presentation project-personal/stage"${i}"
done
